### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by strzibny** [fedora-infra/python-fedora#116]
Hi,

is Python3 support planned? We would like to depend on the API but we want to support both Python3/2.

**Comment by pypingou** [comment]
To which part of the API do you want to rely?

**Comment by ralphbean** [comment]
It is planned... but like @pypingou suggests, we won't be able to cover the entire package (some thing depend on TurboGears1 components which themselves will never be ported to Python3).

We ported python-kitchen to python3 last year to get ready for this and I think it's one of the things we're going to work on at the PyCon US sprints in April this year.

**Comment by strzibny** [comment]
Well, I wanted to talk to Bodhi. In the meantime I reconstructed a part of that API for my needs. But with Bodhi 2 being prepared I would then like to use it for Bodhi 2 ideally. (And actually we now support both Python 2 and 3 which makes things insane:/)
