### ISSUE TITLE
python-six on RHEL7 does not contain urllib move

### ISSUE THREAD

**Issue by puiterwijk** [fedora-infra/python-fedora#132]

**Comment by lmacken** [comment]
What version of python-six?

**Comment by puiterwijk** [comment]
Latest in RHEL7: python-six-1.3.0-4.el7

**Comment by ralphbean** [comment]
We even have a [tox test suite](https://github.com/fedora-infra/python-fedora/blob/develop/tox.ini) designed to catch this, but I guess it wasn't run when that change was made?

**Comment by ralphbean** [comment]
Done.

**Comment by scop** [comment]
7.2 has 1.9.0.
