### ISSUE TITLE
It appears that `fedora.client.pkgdb.PackageDB` isn't compatible wiht pkgdb2

### ISSUE THREAD

**Issue by tomprince** [fedora-infra/python-fedora#162]
At least `.user_packages` no longer works (used by `fedmsg-notify`).

**Comment by pypingou** [comment]
That is true, the pkgdb client is now part of https://github.com/fedora-infra/packagedb-cli

**Comment by pypingou** [comment]
Btw, what do you mean ``used by fedmsg-notify``?

**Comment by ralphbean** [comment]
Probably [this](https://github.com/fedora-infra/fedmsg-notify/blob/develop/fedmsg_notify/distro_specific/_fedora.py#L37-L44)?

**Comment by ralphbean** [comment]
So, we need to retire `fedora.client.pkgdb.PackageDB` if things have moved out to 'packagedb-cli'.

**Comment by pypingou** [comment]
I would say 'probably yes' to both :)

**Comment by TridevGuha** [comment]
Hi, how to start with this issue?

**Comment by abadger** [comment]
Fixed by @ralphbean here: https://github.com/fedora-infra/python-fedora/commit/cbe202471b58ec877b0a9407d6f05edf993ce767

Closing issue.
