### ISSUE TITLE
AuthError not raised on 403 errors

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/python-fedora#196]
I noticed today that the [```fedora.client.openidbaseclient.requires_login``` decorator](https://github.com/fedora-infra/python-fedora/blob/0.8.0/fedora/client/openidbaseclient.py#L60-L87) does not handle 403 return codes though it looks like it's intended to. The issue is that the output variable (a ```requests.models.Response```) does two weird things:

1. It casts to False:

```
ipdb> bool(output)
False
```

2. "anding" a ```Response``` with a ```bool``` does not return a bool:

```
ipdb> print (output and output.status_code)                                                                           
<Response [403]>
```

We probably want to do this instead:

```
elif hasattr(output, 'status_code') and output.status_code == 403:
```

**Comment by pypingou** [comment]
``bool(output)`` is I think a documented feature, everything that is not a 20* code will return ``False``.

The ``anding`` though it a little more odd for the least

**Comment by pypingou** [comment]
Isn't the idea of this line to protect against output being None? If so should we make it ``elif output is not None and output.status_code == 403`` ?

**Comment by bowlofeggs** [comment]
@pypingou Yeah probably, though hasattr on None will also be False. Either way should work.

**Comment by jeremycline** [comment]
Just a heads-up, the ``__bool__`` method is gone from Response objects in requests-3.0 and code that wants to transition smoothly shouldn't rely on it: https://github.com/kennethreitz/requests/issues/2002
