### ISSUE TITLE
fedora.client.OpenIdBaseClient: does not support kerberos

### ISSUE THREAD

**Issue by nmav** [fedora-infra/python-fedora#202]
That is, it is not possible to authenticate using the bodhi command line application and a valid kerberos ticket. That prevents:
 * A smooth developer workflow with a kerberos ticket used to authenticate all fedora-related operations (i.e., koji and bodhi)
 * A secure and non-interactive developer workflow as in https://github.com/cockpit-project/cockpituous/ (current setups require storing the bodhi password).

**Comment by puiterwijk** [comment]
This is as intended, and Bodhi will be moving to OpenID Connect instead.
The current fedora.client authentication code will be deprecated over time.
