### ISSUE TITLE
Now that Flask 1.0.0 is out, the test line 115 in flask_fas_openid is wrong

### ISSUE THREAD

**Issue by abompard** [fedora-infra/python-fedora#211]
With Flask >= 1.0.0 and < 1.10.0, the test used to activate the specific JSON encoder in flask_fas_openid is wrong:
https://github.com/fedora-infra/python-fedora/blob/80be6f8af31b55888a8004ab2879e8e249238cc0/flask_fas_openid.py#L115

This should be `if assume_recent or major >= 0 or minor >= 10:` because `major` is `1` and `minor` is `0`.

**Comment by pypingou** [comment]
Proposed PR at: https://github.com/fedora-infra/python-fedora/pull/208

**Comment by abompard** [comment]
Fixed in PR #208
